apiVersion: v1
kind: Pod ## or job
metadata:
  namespace: user-daniel-calovi # your name space
  name: daniel-calovi-deeplabcut #your pod/job name
spec:
  containers:
  - name: daniel-calovi-deeplab-ownssh
    image: ccu-k8s.inf.uni-konstanz.de:32250/daniel.calovi/dlc_image
    command: ["/bin/bash","-c"]
    args:
    - |
      /usr/sbin/sshd
      while true; do sleep 3600; done; # Keeps container running
    resources:
      requests:
        cpu: 32
        nvidia.com/gpu: 1
        memory: 160Gi
      limits:
        cpu: 32
        nvidia.com/gpu: 1
        memory: 160Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
      - mountPath: "/abyss/home/pumbaa"
        name: samba-share
        readOnly: false
  imagePullSecrets:
  - name: regcredjson
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/daniel-calovi"
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
    - name: samba-share
      flexVolume:
        driver: "fstab/cifs"
        fsType: "cifs"
        secretRef:
          name: "cifs-secret"
        options:
          networkPath: "//timon.cascb.uni-konstanz.de/Multimedia"
          mountOptions: "vers=3.0,dir_mode=0755,file_mode=0644,noperm"

