apiVersion: v1
kind: Pod ## DSC or job
metadata:
  namespace: user-daniel-calovi		#DSC your name spac
  name: deeplabcut-ccu 			#DSC your pod/job name
spec:
  containers:
  - name: dlc-ccu
    image: ccu-k8s.inf.uni-konstanz.de:32250/daniel.calovi/dlc_ccu #DSC Container address
    command: ["/bin/bash","-c"]
    args:
    - |
      sh /home/First_Execute.sh
      while true; do sleep 3600; done; # Keeps container running
    resources:
      requests:
        cpu: 1
        nvidia.com/gpu: 1
        memory: 10Gi
      limits:
        cpu: 1
        nvidia.com/gpu: 1
        memory: 10Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
      - mountPath: /local		#DSC Mount ephemeral local storage
        name: local-storage		#DSC Mount ephemeral local storage
        readOnly: false			#DSC Mount ephemeral local storage
      - mountPath: "/abyss/home/timon"	#DSC Mount DMP storage
        name: samba-share		#DSC Mount DMP storage
        readOnly: false			#DSC Mount DMP storage
  imagePullSecrets:			#DSC Your secret for the ccurepository
  - name: regcredjson			#DSC Your secret for the ccurepository
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/daniel-calovi" #DSC your home path
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
    - name: local-storage
      hostPath:
        path: "/raid/local-data/daniel-calovi"				#DSC Mounting ephemeral storage
        type: DirectoryOrCreate						#DSC Mounting ephemeral storage
    - name: samba-share							#DSC Mounting your DMP storage
      flexVolume:							#DSC Mounting your DMP storage
        driver: "fstab/cifs"						#DSC Mounting your DMP storage
        fsType: "cifs"							#DSC Mounting your DMP storage
        secretRef:							#DSC Mounting your DMP storage
          name: "cifs-secret"						#DSC Mounting your DMP storage
        options:							#DSC Mounting your DMP storage
          networkPath: "//timon.cascb.uni-konstanz.de/Multimedia"      	#DSC Mounting your DMP storage
          mountOptions: "vers=3.0,dir_mode=0755,file_mode=0644,noperm" 	#DSC Mounting your DMP storage

