apiVersion: v1
kind: Pod                                 #DSC change here for jobs
metadata:
  namespace: user-name-space              #DSC change here namespace
  name: ccu-deeplabcut                    #DSC change here pod name
spec:
  containers:
  - name: daniel-calovi-deeplab-ownssh     ##DSC change here
    image: git.cascb.uni-konstanz.de/0000-0002-2452-9801/dlc_ccu30_xpra
    command: ["/bin/bash","-c"]
    args:
    - |
      /usr/sbin/sshd
      while true; do sleep 3600; done; # Keeps container running
    #args: ["while true; do sleep 30; done;"] # Keeps the container running
    resources:
      requests:
        cpu: 10
        nvidia.com/gpu: 1
        memory: 100Gi
      limits:
        cpu: 10
        nvidia.com/gpu: 1
        memory: 100Gi
    volumeMounts:
      - mountPath: /abyss/home
        name: cephfs-home
        readOnly: false
      - mountPath: /abyss/shared
        name: cephfs-shared
        readOnly: false
      - mountPath: /abyss/datasets
        name: cephfs-datasets
        readOnly: true
      - mountPath: "/abyss/home/pumbaa"             #DSC change here CASCB storage mounting
        name: samba-share			    #DSC change here CASCB storage mounting
        readOnly: false 			    #DSC change here CASCB storage mounting
  imagePullSecrets:
  - name: yoursecretename      			    #DSC change here for pull secrets
  volumes:
    - name: cephfs-home
      hostPath:
        path: "/cephfs/abyss/home/name-space"        #DSC change here your home
        type: Directory
    - name: cephfs-shared
      hostPath:
        path: "/cephfs/abyss/shared"
        type: Directory
    - name: cephfs-datasets
      hostPath:
        path: "/cephfs/abyss/datasets"
        type: Directory
    - name: samba-share			
      flexVolume:
        driver: "fstab/cifs"
        fsType: "cifs"
        secretRef:
          name: "cifs-secret"
        options:
          networkPath: "//Pumbaa.cascb.uni-konstanz.de/YourFolderHere"  #DSC change here CASCB storage mounting
          mountOptions: "vers=3.0,dir_mode=0755,file_mode=0644,noperm,domain=CASCB"
